### ISSUE TITLE
Auto benchmark summary report

### ISSUE THREAD

**Issue by shps951023** [mini-software/MiniExcel#753]

**Comment by michelebastione** [comment]
@shps951023 Do you intend to create some sort of workflow for the benchmarks?

**Comment by shps951023** [comment]
> [@shps951023](https://github.com/shps951023) Do you intend to create some sort of workflow for the benchmarks?

Yes, because after several version optional function, the performance is slower than before.
I would like there's auto performance benchmark to avoid that.

**Comment by michelebastione** [comment]
That's a neat idea. I'm actually working on refactoring the tests and the benchmarks, maybe I can look into this as well. On that note do you mind if I PR a big change to the tests while you work on fixing the template optimization?

**Comment by shps951023** [comment]
> That's a neat idea. I'm actually working on refactoring the tests and the benchmarks, maybe I can look into this as well. On that note do you mind if I PR a big change to the tests while you work on fixing the template optimization?

👍👍 Please, I'll fix the template optimization today

**Comment by michelebastione** [comment]
Working on the benchmarks I noticed that it already exports the results in a .md file, so we could simply add that to the repository at the end of the benchmark 

```yml
name: MiniExcel Benchmark

on:
  push:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 9.0.x
    - name: Restore dependencies
      working-directory: ./benchmarks/MiniExcel.Benchmarks
      run: dotnet restore
    - name: Build
      working-directory: ./benchmarks/MiniExcel.Benchmarks
      run: dotnet build --no-restore
    - name: Benchmark
      working-directory: ./benchmarks/MiniExcel.Benchmarks
      run: dotnet run -c Release -f net9.0
    - name: Commit report
      working-directory: ./benchmarks/MiniExcel.Benchmarks/BenchmarkDotNet.Artifacts/results
      run: |
           git add MiniExcelLibs.Benchmarks.XlsxBenchmark-report-github.md
           git commit -am "Automated benchmark report"
           git push
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
``` 

I'm not sure about the last part, I'm not very familiar with github actions and I don't know how to setup the token, but it looked good to me, at least as a draft
